# Generated by Django 5.2.4 on 2025-07-19 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="slug",
            field=models.SlugField(default="temp", max_length=150),
            preserve_default=False,
        ),
    ]
