# Generated by Django 5.2.4 on 2025-08-11 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0004_review"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
