# Generated by Django 5.2.4 on 2025-10-04 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="payment_event_id",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("sslcommerz", "SSLCOMMERZ"),
                    ("stripe", "Stripe"),
                    ("stripe_custom", "Stripe Custom"),
                    ("balance", "Balance"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
